//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommentCleanerWPF {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class RegexSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static RegexSettings defaultInstance = ((RegexSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new RegexSettings())));
        
        public static RegexSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[\\t\\s]+(//(?![!/])).*?$~Multiline~.cs")]
        public string CSFileBasicExp {
            get {
                return ((string)(this["CSFileBasicExp"]));
            }
            set {
                this["CSFileBasicExp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[\\t\\s]*/\\*[^!].*?\\*/~Singleline~.cs")]
        public string CSFileMultiExp {
            get {
                return ((string)(this["CSFileMultiExp"]));
            }
            set {
                this["CSFileMultiExp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[\\t\\s]*<!--[^#].*-->~Multiline~.xaml")]
        public string XAMLFileMultiExp {
            get {
                return ((string)(this["XAMLFileMultiExp"]));
            }
            set {
                this["XAMLFileMultiExp"] = value;
            }
        }
    }
}
